### ISSUE TITLE
Porque um bundle com todo JS para uma app SPA?

### ISSUE THREAD

**Issue by alexsandro-xpt** [blogmv/backbone-browserify#1]
Estou lendo seu post em http://www.rcarvalhojs.com/javascript/2014/09/01/backbone-browserify.html e me veio esta dúvida.

Por se tratar de uma app SPA, não é mais interessante acontecer load de .js a cada navegação da app?

Pois imagine se o bundle.js fica 500kb ou mais?

Com proceder neste caso com o browserify?

Obrigado.

**Comment by chiefGui** [comment]
O Browserify tem este déficit—ele não faz gerenciamento de recursos sob demanda, o que naturalmente vai gerar o bundle e por sua vez sobrecarregar a sua (primeira) requisição.

Por isso, o mundo conheceu o [webpack](http://webpack.github.io/): além de gerenciar todos os seus assets—desde css e javascript, até fontes e imagens—, você ganha, de praxe, a habilidade de lidar com todos os seus scripts "on the fly", utilizando a sua sintaxe preferida, modular, assíncrona ou ambas.

Para aplicações SPA de pequeno e médio porte, onde comumente a quantidade de scripts é pequena, o Browserify é suficiente—você começaria a sentir o custo dele quando você tiver que escalar. Portanto, se a sua aplicação é pequena, Browserify cumpre muito bem o seu papel; a partir do momento que ela escala, prefira outro module bundler. Até agora, quem está em alta por justamente lidar com alta latência, é o webpack.

Para que fique claro, vamos fragmentar a sua pergunta:

> Pois imagine se o bundle.js fica 500kb ou mais?
> 
> Com proceder neste caso com o browserify?

Não tem como proceder. É para isso que o Browserify serve—compactar, em um arquivo só, todo o seu conteúdo JavaScript. Eis a diferença de para AMD, que carrega os seus scripts sob demanda, quando necessário, se necessário. Um exemplo de gerenciador JavaScript assíncrono é o [Require.js](http://requirejs.org/).

### Ué, mas e o webpack?

Independente da sintaxe escolhida—`var foo = require ('foo')` ou `require(['foo'], function(foo){})`—, o webpack faz _code splitting_, que é dividir uma certa demanda de scripts em "chunks"—entenda como "pedaços"—, e então distribui este pedaço quando for preciso. Ou seja, caso o seu `/index.html` exija somente alguns scripts, é possível distribuir só aqueles pedaços para aquela requisição, dispensando toneladas de linhas de código sem necessidade.

Para lhe contextualizar, vamos considerar que você tenha a seguinte estrutura de pastas:

```
- app/
  |-- js/
     |-- app.js
     |-- pages/
        |-- index.js
        |-- contact.js
- node_modules/
   |-- jquery/
      |-- jquery.js
```

Através das chunks, tendo como `app.js` o seu ponto de entrada, você consegue especificar que quando o cliente acessar `/index`—através de um mecanismo de rotas qualquer—, apenas os arquivos `app.js`, `index.js` e `jquery.js` serão carregados. O melhor dos dois mundos: CommonJS e AMD.

Mas atenção: isso não necessariamente acontece de forma assíncrona—o webpack não vai lidar com o carregamento recorrente dos seus arquivos. Na verdade, ele gera bundles baseados nos chunks, algo que na minha opinião é (relativamente) mais consistente que a invocação assíncrona porque a distribuição não é arbitrária.

Caso você queira entender melhor, [a documentação é bem clara](http://webpack.github.io/docs/code-splitting.html).

**Comment by alexsandro-xpt** [comment]
Pelo visto, então o Browserify não o ideal para o que eu gostaria. Preciso escrever um web app grande em SPA consumindo uma API REST, talvez se eu investir em webpack é a minha melhor opção.

Eu já trabalhei um tempo com RequireJS, mas ando percebendo que os desenvolvedores estão usando outros como o próprio Browserify e Webpack.

Penso também que se eu usar o Browserify, eu nao preciso necessariamente criar um bundle no final do projeto. Mas nunca vi ninguém dando esta dica.

Eu gostei desta explicação sobre o Webpack, vou ler mais a respeito e provavelmente adotarei-o.

E sobre seu exemplo acima, vamos complementar:

```
- app/
  |-- js/
     |-- app.js
     |-- pages/
        |-- index
            |-- index.js
            |-- form.js
            |-- component1.js
        |-- contact
            |-- contact.js
- node_modules/
   |-- jquery/
      |-- jquery.js
```

Posso considerar que o chunks para página `index.html` seria um bundle dos seguintes arquivos `index.js`, `form.js`, `component1.js`?

Pois `app.js` e `jquery.js` seriam um outro bundle pois este chunks so seriam carregado e executado uma unica vez, que é a primeira vez que a web app for acessada.

Qual é sua opnião? Obrigado!

**Comment by chiefGui** [comment]
> Posso considerar que o chunks para página index.html seria um bundle dos seguintes arquivos index.js, form.js, component1.js?

Sim.

> Pois app.js e jquery.js seriam um outro bundle pois este chunks so seriam carregado e executado uma unica vez, que é a primeira vez que a web app for acessada.

Sim. Mas caso alguma chunk dependa do `jquery.js`, por exemplo, na primeira vez ele será incluso nos scripts carregados para a página solicitada.

Em outras palavras, com webpack e code splitting você tem controle total sobre quais e quando os seus scripts serão carregados. E diferente das requisições concorrentes do AMD, isso será através de bundles—economizando a quantidade de requisições. Ou seja, você terá sim (relativamente) grandes arquivos mas apenas com o código necessário para rodar uma requisição específica da sua aplicação.

Para aplicações de grande porte, como já falado, webpack é uma boa pedida. Além disso, baseado na sua necessidade, ele é uma solução.

> Penso também que se eu usar o Browserify, eu nao preciso necessariamente criar um bundle no final do projeto. Mas nunca vi ninguém dando esta dica.

Em ambiente de desenvolvimento eu sei que isso é possível, mas nunca vi code splitting em produção.

**Comment by alexsandro-xpt** [comment]
Bacana, Webpack é o caminho então. Muito obrigado!!

**Comment by fczuardi** [comment]
Browserify com as opções standalone e exclude consegue o mesmo resultado. É apenas questão de preferência e de saber usar a ferramenta :)

**Comment by alexsandro-xpt** [comment]
Eu já usei o RequireJS e gostava, porem para SPA nunca tinha usado e tecnicamente me parecia fora de mão.

Procurei pelo Browserify, mas nao cheguei a testar.

Com o esclarecimento do @chiefGui acima, ele mostrou mais interessante o Webpack e então fui estuda-lo. E com meus teste, realmente o resultado foi surpreendente, estou gostando muito com o resultado.

No inicio eu achei complicado entender ao certo como Webpack funciona otimizdamente, mas agora tudo está mais claro.

Recomendo fortemente o Webpack.

**Comment by chiefGui** [comment]
@fczuardi podes me dar um exemplo?

@alexsandro-xpt show :+1:

**Comment by fczuardi** [comment]
@chiefGui posso sim, no [handbook do browserify](https://github.com/substack/browserify-handbook#bundling) e no [guia de browserify para usuários de webpack](https://gist.github.com/substack/68f8d502be42d5cd4942) ja tem alguns, mas posso montar um exemplo extra mais específico com a estrutura e arquivos do seu primeiro reply…

**Comment by alexsandro-xpt** [comment]
Interessante em @fczuardi deu até vontade de testar o browserify para eu fazer uma comparação melhor em relação ao webpack.

Unica coisa que não consegui ver direito ainda é sobre o uso de CDN para os vendors que configurei no webpack. Parece que não tem suporte nativo.

**Comment by fczuardi** [comment]
@chiefGui postei um exemplo aqui https://github.com/fczuardi/exemplo-browserify

**Comment by zigolis** [comment]
Estou modificando a tag de issue para question.
